version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 1972:1972
      - 2188:2188
      - 51773:51733
      - 52773:52773
      - 53773:53773
    volumes:
      - ./:/irisdev/app